# Workflow ensures samples are build-able and do not drift from the core API

name: samples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sample: [crud, migrate, overview, packed, sensedeep, typescript]

    defaults:
      run:
        working-directory: ./samples/${{ matrix.sample }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: make configure
      - run: make build
      - run: make run
